# Xamarin.Android
# Build a Xamarin.Android project.
# Add steps that test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xamarin

trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'
  outputDirectory: '$(build.binariesDirectory)/$(buildConfiguration)'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  displayName: 'Restore packages'
  inputs:
    restoreSolution: '**/*.sln'

- task: XamarinAndroid@1
  displayName: 'Build Android'
  inputs:
    projectFile: 'AuthenticatorPro.Droid/AuthenticatorPro.Droid.csproj'
    outputDirectory: '$(outputDirectory)/android'
    configuration: '$(buildConfiguration)'

- task: XamarinAndroid@1
  displayName: 'Build Wear OS'
  inputs:
    projectFile: 'AuthenticatorPro.WearOS/AuthenticatorPro.WearOS.csproj'
    outputDirectory: '$(outputDirectory)/wearos'
    configuration: '$(buildConfiguration)'

- task: AndroidSigning@3
  displayName: 'Sign APKs'
  inputs:
    apkFiles: '$(outputDirectory)/*/*.apk'
    apksign: true
    zipalign: true
    apksignerKeystoreFile: 'jmh.keystore'
    apksignerKeystorePassword: $(keystore.password)
    apksignerKeystoreAlias: $(keystore.alias)
    apksignerKeyPassword: $(key.password)
    
- task: DotNetCoreCLI@2
  displayName: 'Run tests'
  inputs:
    command: 'test'
    arguments: '--configuration $(buildConfiguration)'
    publishTestResults: true
    projects: 'AuthenticatorPro.Test/AuthenticatorPro.Test.csproj'

- task: PublishBuildArtifacts@1
  displayName: 'Publish artifacts'
  condition: succeeded()
  inputs:
    pathtoPublish: '$(outputDirectory)'