files:
  - source: /AuthenticatorPro/Resources/values/strings.xml
    translation: /AuthenticatorPro/Resources/values-%two_letters_code%/strings.xml
    languages_mapping:
      two_letters_code:
        zh-CN: zh-rCN
        zh-TW: zh-rTW